In [16]:
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
baseline = pd.read_csv("../results/baseline_results.csv")
fasttext = pd.read_csv("../results/fasttext_results.csv")
indobert = pd.read_csv("../results/indobert_results.csv")
xlmr = pd.read_csv("../results/xlmr_results.csv")

In [18]:
comparison = pd.concat(
    [baseline, fasttext, indobert, xlmr],
    ignore_index=True
)

In [19]:
comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

comparison.insert(0, "Rank", range(1, len(comparison)+1))

comparison

,Rank,Model,Accuracy,Precision,Recall,F1 Score,F1,F1-Score
0,1,IndoBERT,0.986000,0.992000,0.979000,NaN,NaN,0.985
1,2,XLM-R,0.978000,0.987000,0.969000,NaN,NaN,0.977
2,3,TF-IDF and Logistic Regression,0.932161,0.934143,0.932161,0.931986,NaN,NaN
3,4,FastText,0.481156,0.231511,0.481156,NaN,0.312608,NaN

In [20]:
comparison.to_csv(
    "../results/model_comparison.csv",
    index=False
)

In [21]:
comparison

,Rank,Model,Accuracy,Precision,Recall,F1 Score,F1,F1-Score
0,1,IndoBERT,0.986000,0.992000,0.979000,NaN,NaN,0.985
1,2,XLM-R,0.978000,0.987000,0.969000,NaN,NaN,0.977
2,3,TF-IDF and Logistic Regression,0.932161,0.934143,0.932161,0.931986,NaN,NaN
3,4,FastText,0.481156,0.231511,0.481156,NaN,0.312608,NaN

In [25]:
best = comparison.iloc[0]

print("=" * 50)
print("BEST PERFORMING MODEL")
print("=" * 50)
print(f"Model      : {best['Model']}")
print(f"Accuracy   : {best['Accuracy']:.3f}")
print(f"Precision  : {best['Precision']:.3f}")
print(f"Recall     : {best['Recall']:.3f}")
print(f"F1-Score   : {best['F1-Score']:.3f}")

==================================================
BEST PERFORMING MODEL
==================================================
Model      : IndoBERT
Accuracy   : 0.986
Precision  : 0.992
Recall     : 0.979
F1-Score   : 0.985